### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by rickdtc** [acszo/Redomi#1]
Well, I tap on a link, in my case, a yt music link, redomi's bottom drawer appears, loads for sometime then crashes.

Exception log :
```
FATAL EXCEPTION: main
Process: com.acszo.redomi, PID: 18175
java.util.NoSuchElementException: Collection is empty.
	at y4.n.Q0(Unknown Source:35)
	at b4.f.J(Unknown Source:711)
	at i0.c.a(Unknown Source:45)
	at i0.c.J(Unknown Source:8)
	at y.v1.a(Unknown Source:370)
	at y.v1.K(Unknown Source:16)
	at i0.c.K(Unknown Source:53)
	at y.j3.K(Unknown Source:183)
	at i0.c.K(Unknown Source:53)
	at t5.w.f(Unknown Source:163)
	at y.l3.a(Unknown Source:134)
	at y.w1.J(Unknown Source:455)
	at i0.c.a(Unknown Source:45)
	at k.t.a(Unknown Source:65)
	at k.t.K(Unknown Source:53)
	at a0.p.G(Unknown Source:281)
	at a0.p.L(Unknown Source:57)
	at a0.p.r(Unknown Source:162)
	at a0.p.E(Unknown Source:30)
	at a0.u.y(Unknown Source:21)
	at a0.f2.p(Unknown Source:111)
	at a0.c2.U(Unknown Source:399)
	at androidx.compose.ui.platform.w0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.u0.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: y5.e: [a0.k1@e06fb8e, androidx.compose.ui.platform.t1@7728faf, l1{Cancelling}@3e8afbc, v0@7064b45]
```

[Whole logcat log](https://pastebin.com/eG9JdDxS), started recording logs a little bit before tapping on link

**Comment by acszo** [comment]
Thanks, i'm aware of this silly bug (it happened once yesterday too lol), I'll fix it when I got time along with other stuff

**Comment by rickdtc** [comment]
Alright thanks, sure no prob

**Comment by acszo** [comment]
i fixed it now 🤯

**Comment by rickdtc** [comment]
Let's gooo thanks!
