### ISSUE TITLE
application suspect crash in certain Android version?

### ISSUE THREAD

**Issue by internet-coffee** [acszo/Redomi#20]
### Describe the bug

I have to devices,one is A52s(lineageOS 21 Android 14),the other is Realme C21(Realme Ui 2.0 Android 11).Redomi in A52s works well,but in realme c21 when I tap yt music or other music platform,application seems crash,nothing happened,also didn't open the browser.

https://github.com/user-attachments/assets/66d9741f-0d8a-4c24-81c5-455c32932190

### Expected behavior

open music app or open browser

### Device

Version: 1.3.0
Model: RMX3201
Android: 11 (API 30)

**Comment by acszo** [comment]
It doesn't seem to crash for me on Android 11. Does this happen on the previous version (1.2.3)?

**Comment by ElizabethWega** [comment]
I do not know whether my issue is the same as this one, but whenever I tap 'Youtube Music' (a single song is redirected from a Spotify link to YTM), nothing happens. It is only that after few consecutive attempts that Xiaomi (custom ROM: MIUI V14.0.7.0.TKKCNXM | stable) returns the following bug report:

`android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://music.youtube.com/... sel=act=android.intent.action.MAIN cat=[android.intent.category.APP_BROWSER]} }
	at android.app.Instrumentation.checkStartActivityResult(Unknown Source:137)
	at android.app.Instrumentation.execStartActivity(Unknown Source:210)
	at android.app.Activity.startActivityForResult(Unknown Source:34)
	at bc.startActivityForResult(SourceFile:2)
	at android.app.Activity.startActivityForResult(Unknown Source:1)
	at bc.startActivityForResult(SourceFile:1)
	at android.app.Activity.startActivity(Unknown Source:16)
	at android.app.Activity.startActivity(Unknown Source:1)
	at android.content.ContextWrapper.startActivity(Unknown Source:2)
	at android.content.ContextWrapper.startActivity(Unknown Source:2)
	at C2.K(Unknown Source:94)
	at Kw.b(Unknown Source:8)
	at cR.o(Unknown Source:133)
	at S6.l(Unknown Source:8)
	at ig.R(Unknown Source:80)
	at s9.o(Unknown Source:104)
	at s9.B(Unknown Source:32)
	at s9.l(Unknown Source:16)
	at LQ.x0(Unknown Source:50)
	at LQ.c0(Unknown Source:31)
	at Ca.c0(Unknown Source:110)
	at cB.h(Unknown Source:156)
	at cB.h(Unknown Source:135)
	at cB.h(Unknown Source:135)
	at cB.h(Unknown Source:135)
	at cB.h(Unknown Source:135)
	at o5.h(Unknown Source:35)
	at ra.e(Unknown Source:140)
	at k2.F(Unknown Source:80)
	at k2.j(Unknown Source:380)
	at k2.dispatchTouchEvent(Unknown Source:75)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59)
	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(Unknown Source:0)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(Unknown Source:2)
	at android.app.Dialog.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(Unknown Source:153)
	at android.view.View.dispatchPointerEvent(Unknown Source:16)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:54)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:131)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34)
	at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:171)
	at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:48)
	at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:105)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:119)
	at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:52)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(Unknown Source:17)
	at android.os.Looper.loopOnce(Unknown Source:6)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
	Suppressed: ph: [Zy@2f5bb55, b8@a72d96a, nP{Cancelling}@3210e5b, F3@cd506f8]
`

**Comment by KEVIN970712** [comment]
> It doesn't seem to crash for me on Android 11. Does this happen on the previous version (1.2.3)?

yes,and I try  clear app data,still not working.
I'm not sure whether related to the Android version(this is my guess),I only have two devices can test.

**Comment by KEVIN970712** [comment]
> I do not know whether my issue is the same as this one, but whenever I tap 'Youtube Music' (a single song is redirected from a Spotify link to YTM), nothing happens. It is only that after few consecutive attempts that Xiaomi (custom ROM: MIUI V14.0.7.0.TKKCNXM | stable) returns the following bug report:
> 
> `android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] dat=https://music.youtube.com/... sel=act=android.intent.action.MAIN cat=[android.intent.category.APP_BROWSER]} } at android.app.Instrumentation.checkStartActivityResult(Unknown Source:137) at android.app.Instrumentation.execStartActivity(Unknown Source:210) at android.app.Activity.startActivityForResult(Unknown Source:34) at bc.startActivityForResult(SourceFile:2) at android.app.Activity.startActivityForResult(Unknown Source:1) at bc.startActivityForResult(SourceFile:1) at android.app.Activity.startActivity(Unknown Source:16) at android.app.Activity.startActivity(Unknown Source:1) at android.content.ContextWrapper.startActivity(Unknown Source:2) at android.content.ContextWrapper.startActivity(Unknown Source:2) at C2.K(Unknown Source:94) at Kw.b(Unknown Source:8) at cR.o(Unknown Source:133) at S6.l(Unknown Source:8) at ig.R(Unknown Source:80) at s9.o(Unknown Source:104) at s9.B(Unknown Source:32) at s9.l(Unknown Source:16) at LQ.x0(Unknown Source:50) at LQ.c0(Unknown Source:31) at Ca.c0(Unknown Source:110) at cB.h(Unknown Source:156) at cB.h(Unknown Source:135) at cB.h(Unknown Source:135) at cB.h(Unknown Source:135) at cB.h(Unknown Source:135) at o5.h(Unknown Source:35) at ra.e(Unknown Source:140) at k2.F(Unknown Source:80) at k2.j(Unknown Source:380) at k2.dispatchTouchEvent(Unknown Source:75) at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59) at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620) at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59) at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620) at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59) at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620) at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:59) at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:620) at com.android.internal.policy.DecorView.superDispatchTouchEvent(Unknown Source:0) at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(Unknown Source:2) at android.app.Dialog.dispatchTouchEvent(Unknown Source:2) at com.android.internal.policy.DecorView.dispatchTouchEvent(Unknown Source:153) at android.view.View.dispatchPointerEvent(Unknown Source:16) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:54) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:131) at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:26) at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4) at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0) at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10) at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2) at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7) at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34) at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4) at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0) at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2) at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:34) at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:171) at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:48) at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:105) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:119) at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:52) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(Unknown Source:17) at android.os.Looper.loopOnce(Unknown Source:6) at android.os.Looper.loop(Unknown Source:82) at android.app.ActivityThread.main(Unknown Source:123) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) at com.android.internal.os.ZygoteInit.main(Unknown Source:312) Suppressed: ph: [Zy@2f5bb55, b8@a72d96a, nP{Cancelling}@3210e5b, F3@cd506f8] `

I think it the same,but I can't interpretation the log files.

**Comment by acszo** [comment]
Knew one day the chinese phones would come after me (am cooked). Jokes aside, am not sure why would this happened, on OnueUi, LineageOs and the android emulators I haven't seen this issue. Does this always happen on these devices, like no matter how many different links and platforms you try?

**Comment by KEVIN970712** [comment]
> Knew one day the chinese phones would come after me (am cooked). Jokes aside, am not sure why would this happened, on OneUi, LineageOs and the android emulators I haven't seen this issue. Does this always happen on these devices, like no matter how many different links and platforms you try?

yes.I had try yt music link(covert to spotify) and spotify link(covert to yt msuic), and nothing happen.But I notice when I click covert to apple music,successfully opened the browser.(I don't have installed apple music)

**Comment by acszo** [comment]
Hm, so does that mean it crashes on the apps you have installed? Do you have both spotify and yt music on your phone?

**Comment by ElizabethWega** [comment]
> Hm, so does that mean it crashes on the apps you have installed? Do you have both spotify and yt music on your phone?

I only have YT Music installed.

**Comment by KEVIN970712** [comment]
https://github.com/user-attachments/assets/76f78b20-1d3d-4030-a99e-f66d931ea9c2

**Comment by acszo** [comment]
@KEVIN970712 hmm am not sure, the only way I can reproduce this bug is by not having a Browser installed and trying to open a link from a music platform that I don't have installed on the device. So am not sure how you're getting this issue with the actual app installed that can handle the link. Do Realme and Xiaomi phones have some weird setting that can block apps from redirecting links to other apps? Couldn't find much online either
